#pragma once

/*!
	Game is implemented as a state machine with events - 
	this is a set of available events.
*/
enum E_GAME_EVENT 
{
	EGE_NULL,

	EGE_FRAME_ENDED,

	EGE_APPLICATION_STARTED,

	EGE_GAMELOFT_LOGO_FINISHED,
	EGE_SPLASH_SCREEN_FINISHED,

	EGE_SOUND_ALLOWED,
	EGE_SOUND_PROHIBITED,

	EGE_LEVEL_REQUESTED,
	EGE_SOUND_MENU_REQUESTED,
	EGE_HELP_REQUESTED,
	EGE_ABOUT_REQUESTED,
	EGE_EXIT_REQUESTED,

	EGE_LEVEL_ABORTED,
	EGE_LEVEL_SUCCEEDED,
	EGE_LEVEL_FAILED,

	EGE_LEVEL_CONTINUATION_REQUESTED,
	EGE_MAIN_MENU_REQUESTED,

	EGE_HELP_SCREEN_FINISHED,
	EGE_ABOUT_SCREEN_FINISHED,

	EGE_SUCCESS_SCREEN_FINISHED,
	EGE_FAILURE_SCREEN_FINISHED,

	EGE_APPLICATION_FINISHED,

	EGE_ADDITIONAL_RENDER_STARTING,
	EGE_ADDITIONAL_RENDER_FINISHED,
};